URL: "Google Apps Script URL"

Message:
  BanReason: "Ban Reason"
  Kick: "You are not allowed."
  ErrorDatabase: "Unable to access database."
  sBan: "/sban [PlayerName] [BanReason]"
  unsBan: "/unsban [PlayerName]"
  PlayerNotFound: "Player not found."
